routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

// login
Route::middleware('guest')->group(function () {
    Route::get('/login', [LoginController::class, 'showLogin'])->name('show_login');
    Route::post('/login', [LoginController::class, 'login'])->name('login');
});


// => Protected Routes

Route::middleware(['auth'])->group(function () {

    Route::as('dashboard.')->group(function () {

        Route::middleware(['role:super_admin|merchant'])->group(function () {
            Route::get('/', [DashboardController::class, 'index'])->name('home');
        });
        Route::get('merchant/{id}', [DashboardController::class, 'ShowMerchant'])
            ->name('showMerchant')->middleware('role:super_admin');

        Route::middleware(['role:customer'])->group(function () {
            Route::get('welcome', [DashboardController::class, 'welcome'])->name('welcome');
        });
    });

    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});


Route::fallback(function () {
    return view('errors.404');
});

app/Models/User.php
<?php

namespace App\Models;

use App\Enums\UserTypeEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;
    protected $fillable = [
        'name',
        'email',
        'password',
        'user_type',
        'full_name'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'user_type' => UserTypeEnum::class,
    ];


    /**
     * Check For User Password against a given password
     */
    public function checkPassword(string $coming): bool
    {
        return Hash::check($coming, $this->getPassword());
    }

    public function getPassword(): string
    {
        return $this->password;
    }


    // relationships

    public function users() : HasMany
    {
        return $this->hasMany(User::class, 'user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Enums\UserTypeEnum;
use App\Services\DashboardService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class DashboardController extends Controller
{
    public function __construct(protected DashboardService $homeService)
    {
    }

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        if(checkType(UserTypeEnum::SUPER_ADMIN->value)){
            return view('dashboard.admin')->with($this->homeService->homeData());
        }
        return view('dashboard.merchant')->with($this->homeService->homeData());


    }


    /**
     * @return View|Factory|Application
     */
    public function welcome(): View|Factory|Application
    {
        return view('welcome')->with(['user' => currentUser()]);
    }


    /**
     * @param $id
     * @return Application|View|RedirectResponse
     */
    public function ShowMerchant($id): Application|View|RedirectResponse
    {
        $result = $this->homeService->ShowMerchant($id);
        if (!$result['success']) {
            return back()->withErrors($result['message']);
        }
        return view('merchant.index')->with($result['data']);
    }
}

resources/views/dashboard/admin.blade.php
@extends('layouts.app',['title'=> 'Home'])

@section('content')

    <div class="card mb-5 ">
        <div class="card-header">
            <p>All Merchants With each Users</p>
        </div>
        <div class="card-datatable table-responsive pt-0">
            <table class="datatables-basic table border-top  js-exportable" id="bankTable">
                <thead>
                <tr>
                    <th>#</th>
                    <th class="text-center">Full Name</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Users Count</th>
                    <th class="text-center">Users</th>
                </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                @forelse($list as $data)
                    <tr>
                        <td>{{ ++$loop->index }}</td>
                        <td class="text-center">
                            {{ $data->full_name }}
                        </td>
                        <td class="text-center">
                            {{ $data->email }}
                        </td>
                        <td class="text-center">
                            {{ $data->users_count }}
                        </td>
                        <td class="text-center">
                            <a href="{{ route('dashboard.showMerchant', $data->id) }}">
                               Show Merchant
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">
                            <p class="my-4">
                                No Merchants Exists Yet
                            </p>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            <div class="d-flex justify-content-end">
                {{ $list->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/merchant.blade.php
@extends('layouts.app',['title'=> 'Home'])

@section('content')

    <div class="card mb-5 ">
        <div class="card-header">
            <p>Merchant's Users</p>
        </div>
        <div class="card-datatable table-responsive pt-0">
            <table class="datatables-basic table border-top  js-exportable" id="bankTable">
                <thead>
                <tr>
                    <th>#</th>
                    <th class="text-center">Full Name</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">User Type</th>
                    <th class="text-center">-</th>
                </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                @forelse($list as $data)
                    <tr>
                        <td>{{ ++$loop->index }}</td>
                        <td class="text-center">
                            {{ $data->full_name }}
                        </td>
                        <td class="text-center">
                            {{ $data->email }}
                        </td>

                        <td class="text-center">
                            {{ $data->user_type }}
                        </td>

                        <td class="text-center">
                            -
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">
                            <p class="my-4">
                                No Merchants Exists Yet
                            </p>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            <div class="d-flex justify-content-end">
                {{ $list->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html
    lang="en"
    class="light-style layout-navbar-fixed layout-menu-fixed"
    data-theme="theme-default"
    data-assets-path="{{ asset('assets') }}"
    data-template="vertical-menu-template-no-customizer-starter">
<head>
    <meta charset="utf-8"/>
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />
    <title> {{ env('APP_NAME') }} - {{ $title ?? '' }} </title>

    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="ATM System">
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet" href="{{asset('assets/vendor/fonts/boxicons.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/fonts/fontawesome.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/fonts/flag-icons.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/fonts/fontawesome.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/fonts/flag-icons.css')}}"/>

    <!-- Core CSS -->
    <link rel="stylesheet" href="{{asset('assets/vendor/css/core.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/css/theme-default.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/css/demo.css')}}"/>

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{{asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/libs/typeahead-js/typeahead.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/libs/animate-css/animate.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/vendor/libs/sweetalert2/sweetalert2.css')}}"/>
    <!-- Helpers -->
    <script src="{{asset('assets/vendor/js/helpers.js')}}"></script>
    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <script src="{{asset('assets/js/config.js')}}"></script>
    <!--Toaster -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <!--Select2 -->
    <style>
        /*cairo font*/
        @import "https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;700;900&display=swap";

        body,
        .swal2-title,
        .swal2-actions {
            font-family: 'Cairo', sans-serif !important;
        }
    </style>
    @stack('styles')
</head>

<body>
<!--Loader -->
<div class="overlay__loader">
    <div class="overlay__inner">
        <div class="loader_img">
            <img src="{{asset('assets/img/favicon/favicon.png')}}" style="width: 80%;height: 67px;" alt="Logo">
        </div>
        <div class="loading"></div>
    </div>
</div>
<!-- Layout wrapper -->
<div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
        <!-- Menu -->
        @include('layouts.sidebar')
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
            <!-- Navbar -->
            @include('layouts.navbar')
            <!-- / Navbar -->

            <!-- Content wrapper -->
            <div class="content-wrapper">
                <!-- Content -->

                <div class="container-xxl flex-grow-1 container-p-y">
                    @yield('content')
                </div>
                <!-- / Content -->

                <!-- Footer -->
                <footer class="content-footer footer bg-footer-theme">
                    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                        <div class="mb-2 mb-md-0">
                            &copy;
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <span> {{ env('APP_NAME') }} &reg; </span>
                        </div>
                    </div>
                </footer>
                <!-- / Footer -->

                <div class="content-backdrop fade"></div>
            </div>

            <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->

    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>

    <!-- Drag Target Area To SlideIn Menu On Small Screens -->
    <div class="drag-target"></div>
</div>
<!-- / Layout wrapper -->

<!-- Core JS -->
<!-- build:js assets/vendor/js/core.js -->
<script src="{{asset('assets/vendor/libs/jquery/jquery.js')}}"></script>
<script src="{{asset('assets/vendor/libs/popper/popper.js')}}"></script>
<script src="{{asset('assets/vendor/js/bootstrap.js')}}"></script>
<script src="{{asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js')}}"></script>
<script src="{{asset('assets/vendor/libs/hammer/hammer.js')}}"></script>
<script src="{{asset('assets/vendor/libs/typeahead-js/typeahead.js')}}"></script>
<script src="{{asset('assets/vendor/js/menu.js')}}"></script>

<!-- Main JS -->
<script src="{{asset('assets/js/main.js')}}"></script>
<!--Toaster -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<!-- sweetalert2 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.19.0/sweetalert2.all.min.js"></script>
<!--bootstrap-daterangepicker -->
<script src="{{asset('assets/vendor/libs/moment/moment.js')}}"></script>
@include('shared.alerts')
@include('shared.helpers')


<script>

</script>


@stack('scripts')

</body>
</html>

resources/views/layouts/navbar.blade.php
<nav
    class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar">
    <div class="navbar-nav align-items-center">
        <a class="nav-link style-switcher-toggle hide-arrow" href="javascript:void(0);">
            <i class="bx bx-sm"></i>
        </a>
    </div>

    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <ul class="navbar-nav flex-row align-items-center ms-auto">


            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);"
                   data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        <img src="{{asset('assets/img/avatars/1.png')}}" alt="user"
                             class="w-px-40 h-auto rounded-circle"/>
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="javascript:void(0);">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        <img src="{{asset('assets/img/avatars/1.png')}}" alt="user"
                                             class="w-px-40 h-auto rounded-circle"/>
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <span class="fw-semibold d-block">{{ currentUser()->full_name  }}</span>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="dropdown-item"
                           onclick="$('#logoutForm').submit()">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Logout</span>
                        </a>
                        <form style="display: none" id="logoutForm" method="POST" action="{{ route('logout') }}">
                            @csrf
                            <button type="button" class="btn btn-primary">Logout</button>
                        </form>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        </ul>
    </div>

</nav>

resources/views/layouts/pagination.blade.php
@if ($paginator->hasPages())

    <div class="d-flex flex-sm-fill d-sm-flex align-items-sm-center justify-content-sm-between mx-3">
        <div>
            <p class="small text-muted">
                showing
                <span class="fw-semibold">{{ $paginator->firstItem() }}</span>
                to
                <span class="fw-semibold">{{ $paginator->lastItem() }}</span>
                of
                <span class="fw-semibold">{{ $paginator->total() }}</span>
                results
            </p>
        </div>

        <div>
            <ul class="pagination">
                {{-- Previous Page Link --}}
                @if ($paginator->onFirstPage())
                    <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.previous')">
                        <span class="page-link" aria-hidden="true">@lang('pagination.previous')</span>
                    </li>
                @else
                    <li class="page-item">
                        <a class="page-link" href="{{ $paginator->previousPageUrl() }}" rel="prev"
                           aria-label="@lang('pagination.previous')">@lang('pagination.previous')</a>
                    </li>
                @endif

                {{-- Pagination Elements --}}
                @php
                    $currentPage = $paginator->currentPage();
                    $lastPage = $paginator->lastPage();
                    $pageRange = 4; // Number of pages to show before and after the current page
                    $ellipsis = '<li class="page-item disabled" aria-disabled="true"><span class="page-link">...</span></li>';
                @endphp
                @if ($lastPage <= 7) {{-- Show all page numbers --}}
                @for ($i = 1; $i <= $lastPage; $i++)
                    <li class="page-item {{ ($i == $currentPage) ? 'active' : '' }}"><a class="page-link" href="{{ $paginator->url($i) }}">{{ $i }}</a></li>
                @endfor
                @else {{-- Show ellipsis and range of pages around the current page --}}
                @if ($currentPage <= 4) {{-- First few pages --}}
                @for ($i = 1; $i <= 5; $i++)
                    <li class="page-item {{ ($i == $currentPage) ? 'active' : '' }}"><a class="page-link" href="{{ $paginator->url($i) }}">{{ $i }}</a></li>
                @endfor
                {!! $ellipsis !!}
                <li class="page-item"><a class="page-link" href="{{ $paginator->url($lastPage) }}">{{ $lastPage }}</a></li>
                @elseif ($currentPage >= $lastPage - 3) {{-- Last few pages --}}
                <li class="page-item"><a class="page-link" href="{{ $paginator->url(1) }}">1</a></li>
                {!! $ellipsis !!}
                @for ($i = $lastPage - 4; $i <= $lastPage; $i++)
                    <li class="page-item {{ ($i == $currentPage) ? 'active' : '' }}"><a class="page-link" href="{{ $paginator->url($i) }}">{{ $i }}</a></li>
                @endfor
                @else {{-- Middle pages --}}
                <li class="page-item"><a class="page-link" href="{{ $paginator->url(1) }}">1</a></li>
                {!! $ellipsis !!}
                @for ($i = $currentPage - 1; $i <= $currentPage + 1; $i++)
                    <li class="page-item {{ ($i == $currentPage) ? 'active' : '' }}"><a class="page-link" href="{{ $paginator->url($i) }}">{{ $i }}</a></li>
                @endfor
                {!! $ellipsis !!}
                <li class="page-item"><a class="page-link" href="{{ $paginator->url($lastPage) }}">{{ $lastPage }}</a></li>
                @endif
                @endif
                {{-- Next Page Link --}}
                @if ($paginator->hasMorePages())
                    <li class="page-item">
                        <a class="page-link" href="{{ $paginator->nextPageUrl() }}" rel="next"
                           aria-label="@lang('pagination.next')">@lang('pagination.next')</a>
                    </li>
                @else
                    <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.next')">
                        <span class="page-link" aria-hidden="true">@lang('pagination.next')</span>
                    </li>
                @endif
            </ul>
        </div>
    </div>

@endif

resources/views/layouts/sidebar.blade.php
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo" style="padding-left: 1em !important;">

        <a href="javascript:void(0);" class="app-brand-link">
              <span class="app-brand-logo demo bg-black ">
              <img src="{{asset('assets/img/favicon/favicon.png')}}" alt="{{ env('APP_NAME') }} "
                   class="" style="width: 80%;height: 67px;">
              </span>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-3">
        <!-- Dashboard  -->
        @hasanyrole('super_admin|merchant')
        <li class="menu-item {{  activeClass('dashboard.home')  }}">
            <a href="{{route('dashboard.home')}}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Page 1"> Home </div>
            </a>
        </li>
        @endrole
    </ul>
</aside>

resources/views/merchant/index.blade.php
@extends('layouts.app',['title'=>  $merchant?->full_name . 'details' ])

@section('content')

    <div class="card mb-5 ">
        <div class="card-header">

            <p> Home / <span class="fw-bold"> {{ $merchant?->full_name }}</span></p>

            <p>merchant's users</p>
        </div>
        <div class="card-datatable table-responsive pt-0">
            <table class="datatables-basic table border-top  js-exportable" id="bankTable">
                <thead>
                <tr>
                    <th>#</th>
                    <th class="text-center">Full Name</th>
                    <th class="text-center">Email</th>
                </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                @forelse($users as $user)
                    <tr>
                        <td>{{ ++$loop->index }}</td>
                        <td class="text-center">
                            {{ $user->full_name }}
                        </td>
                        <td class="text-center">
                            {{ $user->email }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">
                            <p class="my-4">
                                No Users Exists Yet
                            </p>
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            <div class="d-flex justify-content-end">
                {{ $users->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/shared/alerts.blade.php
<script>
    @if (session('success'))
     toastr.success("{{ session('success') }}", "done");
    @endif

    @if (session('message'))
    toastr.success("{{ session('message') }}", "done");
    @endif

    @if(session('info'))
    toastr.info("{{ session('info') }}", "info");
    @endif

    @if(session('warning'))
    toastr.warning("{{ session('warning') }}", "warning");
    @endif

    @if ($errors->any())
          @if($errors->get('error'))
            @foreach($errors->get('error') as $error)
            toastr.error("{{$error}}", "error");
           @endforeach
        @else
            @foreach($errors->all() as $error)
            toastr.error("{{$error}}", "error");
            @endforeach
        @endif
    @endif

    function commonError(){
        toastr.error(" something_went_wrong", "error");
    }


</script>

resources/views/shared/helpers.blade.php
<script>
    // Alert With Functional Confirm Button
    function swAlert(link, confirm_button_text = '{{ __('common.swl.are_you_sure') }}', data = null, method = null) {
        Swal.fire({
            title: confirm_button_text,
            // text: text,
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: '{{ __('common.confirm') }}',
            cancelButtonText: '{{ __('common.cancel') }}',
            customClass: {
                confirmButton: 'btn btn-primary me-3',
                cancelButton: 'btn btn-label-secondary'
            },
            buttonsStyling: false
        }).then((result) => {
            if (result.value) {
                location.href = link;
            }
        });
    }


    // form submit
    $('form.submit_form_loader_btn').submit(function (e) {
        let form = $(this);
        let btn = form.find('button[type="submit"]');
        btn.html('<i class="bx bx-loader bx-spin font-size-16 align-middle me-2"></i> {{ __('common.loading') }}');
        btn.attr('disabled', true);
    });


    // Stop Loader
    $(window).on('load', function () {
        $('.overlay__loader').hide();
        $(".form-prevent-multiple-submits").on("submit", function (event) {
            $(".button-prevent-multiple-submits").attr("disabled", true);
            $(".spinner").css("display", "inherit");
        });
    })
</script>